### ISSUE TITLE
typo in "private for argo" radial button mouseover on submit page

### ISSUE THREAD

**Issue by cberys** [cchdo/cchdo.ucsd.edu#12]
These data will only be provided to the Argo program for calibration purposes and will not be public wihtout your permission

should be

These data will only be provided to the Argo program for calibration purposes and will not be public _without_ your permission

**Comment by DocOtak** [comment]
What is the typo exactly?

**Comment by cberys** [comment]
The word "without"

**Comment by DocOtak** [comment]
Ah, I see it now.

**Comment by cberys** [comment]
edited for clarity, is that better?

**Comment by DocOtak** [comment]
Fixed by 05eb951
