### ISSUE TITLE
three things

### ISSUE THREAD

**Issue by githubbuser** [cchdo/cchdo.ucsd.edu#2]
1.  cant click on anything on main menu, like Antarctic,  Pacific, Atlantic,
2.  cant find advanced search on main page
3.  pull down menu under "find data" says Southern Ocean.   Should the main page say "Southern" instead of "Antarctic"?

**Comment by DocOtak** [comment]
I think these have been addressed.

I interpreted "main menu" to be the box on the home page and not the menus at the top, feel free to comment/reopen if this is incorrect.
