### ISSUE TITLE
Add anchors to data pages for major sections

### ISSUE THREAD

**Issue by cberys** [cchdo/cchdo.ucsd.edu#21]
It would be nice if the main sections (Information, Dataset, Data As Received, Data History) had anchors that could be linked to (like on wikipedia)

An email referencing data available as received could link to that specific section.

**Comment by DocOtak** [comment]
The following ids have been added to the cruise page:

-  `cruise-dataset` -> https://cchdo.ucsd.edu/cruise/318M20130321#cruise-dataset
- `cruise-unmerged-data` -> https://cchdo.ucsd.edu/cruise/33RO20150525#cruise-unmerged-data
- `cruise-other-files` -> I cannot think of/find an example
- `cruise-data-history` -> https://cchdo.ucsd.edu/cruise/318M20130321#cruise-data-history
