### ISSUE TITLE
CCHDO homepage:  put the "welcome" first

### ISSUE THREAD

**Issue by sdiggs** [cchdo/cchdo.ucsd.edu#27]
Please put the "Welcome to the CCHDO" box up top on the home page.    Move the "Search" and "Some Starting Searches" down tot the bottom,

![cchdo_homepage_layout_20150730b](https://cloud.githubusercontent.com/assets/12074379/8995907/5994097c-36c9-11e5-932d-fbb0651cd437.png)

**Comment by DocOtak** [comment]
fixed with 78d18d0

**Comment by sdiggs** [comment]
Thanks for taking care of these.
