### ISSUE TITLE
Time series searches need to be more specific.

### ISSUE THREAD

**Issue by sdiggs** [cchdo/cchdo.ucsd.edu#28]
Both the HOT and BATS searches from the homepage are not specific enough.  Each, when invoked give results that aren't specific to either HOT or BATS.  Therefore, each search will need to add "+timeseries" to the URI, like this:

```
 - for HOT: 
              - http://cchdo.ucsd.edu/search?q=HOT+timeseries (only 278 results - HOTS a )
```

![hot1](https://cloud.githubusercontent.com/assets/12074379/8996109/8063fa16-36ca-11e5-93ce-964a153d2cf0.png)

```
              - should be:  http://cchdo.ucsd.edu/search?q=HOT+timeseries (only 265 results - just HOTS )
```

![hot2](https://cloud.githubusercontent.com/assets/12074379/8996132/a917bea2-36ca-11e5-9957-b02c3db4c5d8.png)

**Comment by DocOtak** [comment]
fixed with 70a0ede
