### ISSUE TITLE
Submission page cannot handle non 201 response codes

### ISSUE THREAD

**Issue by cberys** [cchdo/cchdo.ucsd.edu#5]
OS X 10.9.5
Chrome Version 42.0.2311.90 (64-bit)

went to data page for 18HU19820228
/cruise/18HU19820228

hit add data button, redirected to
/submit/for/18HU19820228

From this submit page added:
33RO20130803_ct1.zip

Hit Upload Data
Got 404

This was the ending address:
/submit/for/%3Chtml%3E%3Chead%3E%3Ctitle%3E413%20Request%20Entity%20Too%20Large%3C/title%3E%3C/head%3E%3Cbody%20bgcolor=%22white%22%3E%3Ccenter%3E%3Ch1%3E413%20Request%20Entity%20Too%20Large%3C/h1%3E%3C/center%3E%3Chr%3E%3Ccenter%3Enginx/1.6.3%3C/center%3E%3C/body%3E%3C/html%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E%3C!--%20a%20padding%20to%20disable%20MSIE%20and%20Chrome%20friendly%20error%20page%20--%3E

**Comment by DocOtak** [comment]
Nginx on the test server was configured to accept uploads of only up to 1MB, I'm going to leave this issue open for two reasons:
1. Non 201 responses from the server are currently unhanded by the submission form, any non 201 response indicates an error and this should be indicated to the user.
2. A good default nginx config should be included with the source

**Comment by DocOtak** [comment]
Additionally, it is possible for the network to disconnect before the XHR is sent, in which case, the page will show 0 bytes sent forever.

**Comment by DocOtak** [comment]
Fixed by 09ea457
